default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  port: 5432
  database: alephamine_development
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

test:
  <<: *default
  host: localhost
  port: 5432
  database: alephamine_test
  username: postgres
  password: password

production:
  <<: *default
  database: alephamine_production
  host: <%= ENV['DATABASE_PROD_HOST'] %>
  port: 5432
  username: <%= ENV['DATABASE_PROD_USERNAME'] %>
  password: <%= ENV['DATABASE_PROD_PASSWORD'] %>
