# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.0'

gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'cancancan'
gem 'damerau-levenshtein'
gem 'doorkeeper'
gem 'exponent-server-sdk'
gem 'interactor-rails'
gem 'jbuilder', '~> 2.7'
gem 'nokogiri'
gem 'pg', '~> 1.1'
gem 'pg_search'
gem 'puma', '~> 5.0'
gem 'rack-cors'
gem 'rails', '~> 6.1.1'
gem 'redis', '~> 4.0'
gem 'rexml'
gem 'selenium-webdriver'
gem 'sidekiq'
gem 'whenever'

group :development, :test do
  gem 'annotate'
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'database_cleaner'
  gem 'dotenv-rails'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'hirb'
  gem 'rspec_junit_formatter'
  gem 'rspec-rails', '~> 4.0.2'
  gem 'rubocop-rails', require: false
  gem 'shoulda-matchers'
  gem 'simplecov', '~> 0.10', '< 0.18'
end

group :development do
  gem 'listen', '~> 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
