export const WATCH_BOOK = "WATCH_BOOK";
export const WATCH_BOOK_SUCCESS = "WATCH_BOOK_SUCCESS";
export const WATCH_BOOK_FAIL = "WATCH_BOOK_FAIL";

export const FETCH_WATCHED = "FETCH_WATCHED";
export const FETCH_WATCHED_SUCCESS = "FETCH_WATCHED_SUCCESS";
export const FETCH_DISMISSED_SUCCESS = "FETCH_DISMISSED_SUCCESS";
export const FETCH_WATCHED_FAIL = "FETCH_WATCHED_FAIL";

export const DISMISS_BOOK = "DISMISS_BOOK";
export const DISMISS_BOOK_SUCCESS = "DISMISS_BOOK_SUCCESS";
export const DISMISS_BOOK_FAIL = "DISMISS_BOOK_FAIL";

export const RESTORE_BOOK = "RESTORE_BOOK";
export const RESTORE_BOOK_SUCCESS = "RESTORE_BOOK_SUCCESS";
export const RESTORE_BOOK_FAIL = "RESTORE_BOOK_FAIL";
