export const WATCH_BOOK = "WATCH_BOOK";
export const WATCH_BOOK_SUCCESS = "WATCH_BOOK_SUCCESS";
export const WATCH_BOOK_FAIL = "WATCH_BOOK_FAIL";

export const FETCH_WATCHED = "FETCH_WATCHED";
export const FETCH_WATCHED_SUCCESS = "FETCH_WATCHED_SUCCESS";
export const FETCH_WATCHED_FAIL = "FETCH_WATCHED_FAIL";
